name = "Latin"
uuid = "1e3032c9-fa1e-4efb-a2df-a06f238f6146"
authors = ["nsmith "]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Orthography = "0b4c9448-09b0-4e78-95ea-3eb3328be36d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Documenter = "0.26"
DocStringExtensions = "0.8"
Orthography = "0.4"
